import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {categories,closedStates,transitions,analyze,distance,sla,priority} from './civic-domain.mjs';

const ROOT=path.dirname(fileURLToPath(import.meta.url)), PORT=Number(process.env.PORT||8081), DEMO=process.env.CIVIC_DEMO!=='false';
const DATA=process.env.CIVIC_DATA_DIR||path.join(os.homedir(),'Documents','Codex','civic-os-data');
mkdirSync(DATA,{recursive:true});mkdirSync(path.join(DATA,'evidence'),{recursive:true});
const db=new DatabaseSync(path.join(DATA,'civic.sqlite'));db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
db.exec(`CREATE TABLE IF NOT EXISTS migrations(version INTEGER PRIMARY KEY,applied_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,department TEXT,team TEXT,password TEXT);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),csrf TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS incidents(id TEXT PRIMARY KEY,category TEXT NOT NULL,status TEXT NOT NULL,department TEXT NOT NULL,severity TEXT NOT NULL,lat REAL NOT NULL,lng REAL NOT NULL,ward TEXT NOT NULL,created_at INTEGER NOT NULL,deadline INTEGER NOT NULL,data TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS incident_status ON incidents(status,department,severity); CREATE INDEX IF NOT EXISTS incident_created ON incidents(created_at); CREATE INDEX IF NOT EXISTS incident_sla ON incidents(deadline); CREATE INDEX IF NOT EXISTS incident_geo ON incidents(lat,lng); CREATE INDEX IF NOT EXISTS incident_ward ON incidents(ward);
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),incident_id TEXT REFERENCES incidents(id),created_at INTEGER NOT NULL,data TEXT NOT NULL); CREATE INDEX IF NOT EXISTS report_owner ON reports(user_id,incident_id);
CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTOINCREMENT,incident_id TEXT NOT NULL,actor TEXT NOT NULL,from_state TEXT,to_state TEXT,at INTEGER NOT NULL,note TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,entity TEXT NOT NULL,action TEXT NOT NULL,before_value TEXT,after_value TEXT,at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,incident_id TEXT,title TEXT NOT NULL,at INTEGER NOT NULL,read INTEGER NOT NULL DEFAULT 0); CREATE INDEX IF NOT EXISTS notification_user ON notifications(user_id,at);
CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,incident_id TEXT,kind TEXT NOT NULL,mime TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS participation(user_id TEXT NOT NULL,incident_id TEXT NOT NULL,PRIMARY KEY(user_id,incident_id));
CREATE TABLE IF NOT EXISTS idempotency(user_id TEXT NOT NULL,key TEXT NOT NULL,payload TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(user_id,key));
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); INSERT OR IGNORE INTO settings VALUES('emergency','{"active":false,"zones":[],"alerts":[]}');
INSERT OR IGNORE INTO migrations VALUES(1,${Date.now()});`);
const run=(sql,...params)=>db.prepare(sql).run(...params),get=(sql,...params)=>db.prepare(sql).get(...params),all=(sql,...params)=>db.prepare(sql).all(...params);
function tx(fn){db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
function error(status,message){throw Object.assign(new Error(message),{status});}
function audit(u,entity,action,before,after){run('INSERT INTO audit(actor,entity,action,before_value,after_value,at) VALUES(?,?,?,?,?,?)',u.id,entity,action,JSON.stringify(before??null),JSON.stringify(after??null),Date.now());}
function save(i){run('INSERT INTO incidents VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,status=excluded.status,department=excluded.department,severity=excluded.severity,lat=excluded.lat,lng=excluded.lng,ward=excluded.ward,deadline=excluded.deadline,data=excluded.data',i.id,i.category,i.status,i.department,i.severity,i.lat,i.lng,i.ward,i.createdAt,i.deadline,JSON.stringify(i));}
function incident(id){const row=get('SELECT data FROM incidents WHERE id=?',id);if(!row)error(404,'Incident not found');return JSON.parse(row.data);}
function incidentList(){return all('SELECT data FROM incidents ORDER BY created_at DESC LIMIT 5000').map(x=>JSON.parse(x.data));}
function notice(userId,incidentId,title){run('INSERT INTO notifications(id,user_id,incident_id,title,at) VALUES(?,?,?,?,?)',randomUUID(),userId,incidentId,title,Date.now());}
function notifyIncident(i,title){const ids=new Set(all('SELECT user_id FROM reports WHERE incident_id=?',i.id).map(x=>x.user_id));all("SELECT id FROM users WHERE role IN ('city','admin') OR department=?",i.department).forEach(x=>ids.add(x.id));for(const id of ids)notice(id,i.id,title);}
function change(i,next,u,note){if(!transitions[i.status]?.includes(next))error(409,`Cannot change ${i.status} to ${next}`);const prev=i.status;i.status=next;i.updatedAt=Date.now();if(next==='RESOLVED')i.resolvedAt=Date.now();save(i);run('INSERT INTO history(incident_id,actor,from_state,to_state,at,note) VALUES(?,?,?,?,?,?)',i.id,u.id,prev,next,Date.now(),note);audit(u,i.id,'status',prev,next);notifyIncident(i,`${i.title}: ${next.replaceAll('_',' ').toLowerCase()}`);}
const demoUsers=[['city-demo','Ananya Rao','city',null,null],['citizen-demo','Citizen demo','citizen',null,null],['field-demo','Ramesh Kumar','field','Roads','alpha'],['dept-demo','Roads operator','department','Roads',null],['admin-demo','City administrator','admin',null,null],['citizen-other','Another citizen','citizen',null,null]];
if(DEMO)for(const u of demoUsers)run('INSERT OR IGNORE INTO users(id,name,role,department,team) VALUES(?,?,?,?,?)',...u);
if(!DEMO&&process.env.CIVIC_ADMIN_PASSWORD){const salt=randomBytes(16).toString('hex');run('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)','administrator','City administrator','admin',null,null,`${salt}:${scryptSync(process.env.CIVIC_ADMIN_PASSWORD,salt,64).toString('hex')}`);}
const departments=Object.values(categories).filter((v,i,a)=>a.indexOf(v)===i);
const teams=departments.map((d,i)=>({id:i===0?'alpha':`team-${i+1}`,name:i===0?'Alpha · Rapid response':`${d} response team`,department:d,lat:12.975+i*.006,lng:77.607+i*.004,source:'Demo resource location'}));
if(DEMO&&!get("SELECT key FROM settings WHERE key='seeded'"))tx(()=>{
 const now=Date.now();const seeds=[
 ['INC-0023','Pothole','Deep pothole near Indiranagar Metro','100 Feet Road, Indiranagar','Ward 12',12.978,77.6405,'HIGH',43,'TRIAGED',43,'Deep pothole near a school. Citizens describe a two-wheeler safety risk.'],
 ['INC-0024','Garbage','Waste collection overdue','CMH Road, Indiranagar','Ward 12',12.983,77.638,'MEDIUM',12,'ASSIGNED',180,'Overflowing bins beside the market.'],
 ['INC-0025','Water Leakage','Water main leakage','Richmond Road, Ashok Nagar','Ward 14',12.964,77.603,'HIGH',9,'IN_PROGRESS',84,'Water leakage across the main road.'],
 ['INC-0026','Streetlight','Streetlights out on pedestrian route','Ulsoor Lake Road','Ward 8',12.987,77.622,'MEDIUM',7,'TRIAGED',330,'Three lamps out; dark pedestrian path.'],
 ['INC-0027','Drainage','Blocked stormwater drain','Domlur service road','Ward 14',12.96,77.64,'HIGH',18,'ASSIGNED',125,'Waterlogging near main road after rainfall.'],
 ['INC-0028','Traffic','Junction obstruction','MG Road, Trinity Circle','Ward 9',12.972,77.618,'MEDIUM',6,'TRIAGED',240,'Debris reduces the usable road width.'],
 ['INC-0029','Pothole','Road surface repair awaiting confirmation','Church Street','Ward 9',12.976,77.604,'MEDIUM',3,'RESOLVED',120,'Reported road defect; demo resolution pending citizen review.']
 ];
 for(const [id,category,title,location,ward,lat,lng,severity,reportCount,status,minutes,description] of seeds){const i={id,category,title,location,ward,lat,lng,severity,reportCount,status,description,department:categories[category],createdAt:now-7200000,updatedAt:now,deadline:now+minutes*60000,source:'Demo scenario',teamId:status==='ASSIGNED'||status==='IN_PROGRESS'?teams.find(t=>t.department===categories[category])?.id:null,accepted:false,version:1,analysis:{method:'Deterministic rules',at:now,summary:description,imageAnalyzed:false},evidence:[],resolution:status==='RESOLVED'?{notes:'Demo scenario: road repaired; no real evidence supplied.',evidence:[],source:'Demo scenario'}:null};save(i);run('INSERT INTO history(incident_id,actor,from_state,to_state,at,note) VALUES(?,?,?,?,?,?)',id,'system',null,status,now,'Demo scenario initialized');}
 const ri={id:'REP-DEMO-01',incidentId:'INC-0029',category:'Pothole',location:'Church Street',description:'Demo verification scenario',createdAt:now-7200000,source:'Demo scenario'};run('INSERT INTO reports VALUES(?,?,?,?,?)',ri.id,'citizen-demo',ri.incidentId,ri.createdAt,JSON.stringify(ri));notice('citizen-demo','INC-0029','Road repair is ready for your review');run("INSERT INTO settings VALUES('seeded','true')");
});
function canRead(u,i){return ['city','admin','citizen'].includes(u.role)||u.role==='department'&&u.department===i.department||u.role==='field'&&i.teamId===u.team;}
function operator(u,i){if(!['city','admin','department'].includes(u.role)||u.role==='department'&&u.department!==i.department)error(403,'This action requires an authorized operator');}
function ownReport(u,i){if(u.role!=='citizen'||!get('SELECT id FROM reports WHERE incident_id=? AND user_id=?',i.id,u.id))error(403,'Only a reporting citizen can verify this incident');}
function text(v,label,max=2000){if(typeof v!=='string'||!v.trim()||v.length>max)error(400,`${label} is required (maximum ${max} characters)`);return v.trim();}
function reportInput(b){const category=text(b.category,'Category',40);if(!(category in categories))error(400,'Choose a supported category');const lat=Number(b.lat),lng=Number(b.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<6||lat>38||lng<68||lng>98)error(400,'Choose a valid location in India');return {category,description:text(b.description,'Description'),location:text(b.location,'Location',200),ward:typeof b.ward==='string'?b.ward.slice(0,80):'Unassigned ward',lat,lng};}
const clients=new Set();let revision=Date.now();function publish(){revision++;for(const c of clients)c.res.write(`id: ${revision}\nevent: update\ndata: {"revision":${revision}}\n\n`);}
const allowedOrigins=new Set((process.env.CIVIC_ORIGINS||`http://localhost:8080,http://127.0.0.1:8080,http://localhost:${PORT},http://127.0.0.1:${PORT}`).split(','));
const buckets=new Map();function rate(key,max=180){let b=buckets.get(key);if(!b||b.until<Date.now()){b={count:0,until:Date.now()+60000};buckets.set(key,b);}if(++b.count>max)error(429,'Too many requests. Try again in a minute.');}
const sessionKey=req=>/civic_session=([a-f0-9]+)/.exec(req.headers.cookie||'')?.[1];
function session(req){const row=get('SELECT users.*,sessions.csrf,sessions.expires FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=?',sessionKey(req)||'');if(!row||row.expires<Date.now())error(401,'Please sign in to continue');delete row.password;return row;}
function openSession(res,u){const id=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');run('INSERT INTO sessions VALUES(?,?,?,?)',id,u.id,csrf,Date.now()+8*3600000);res.setHeader('Set-Cookie',`civic_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${!DEMO?'; Secure':''}`);return {...u,password:undefined,csrf,demo:DEMO};}
async function body(req){if(!req.headers['content-type']?.startsWith('application/json'))error(415,'Send application/json');let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>7*1024*1024)error(413,'Upload is too large');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{error(400,'Invalid JSON');}}
function dto(i,u){const p=priority(i);return {id:i.id,title:i.title,category:i.category,description:u.role==='citizen'?undefined:i.description,location:i.location,ward:i.ward,lat:i.lat,lng:i.lng,status:i.status,severity:i.severity,department:i.department,reportCount:i.reportCount,createdAt:i.createdAt,updatedAt:i.updatedAt,deadline:i.deadline,resolvedAt:i.resolvedAt,teamId:u.role==='citizen'?undefined:i.teamId,accepted:i.accepted,version:i.version,source:i.source,priority:p,sla:sla(i),analysis:i.analysis,resolution:i.resolution?{notes:i.resolution.notes,at:i.resolution.at,evidence:u.role==='citizen'&&!get('SELECT id FROM reports WHERE user_id=? AND incident_id=?',u.id,i.id)?[]:i.resolution.evidence,source:i.resolution.source}:null};}
async function route(req,res,url){const pathname=url.pathname;
 if(pathname==='/api/health')return {ok:true,demo:DEMO,storage:'SQLite',realtime:'SSE'};
 if(pathname==='/api/session'&&req.method==='GET'){try{return {...session(req),demo:DEMO};}catch{return {user:null,demo:DEMO};}}
 if(pathname==='/api/demo/session'&&req.method==='POST'){if(!DEMO)error(404,'Not found');const b=await body(req);const u=get('SELECT * FROM users WHERE id=?',b.account);if(!demoUsers.some(x=>x[0]===b.account)||!u)error(400,'Choose a demo account');if(sessionKey(req))run('DELETE FROM sessions WHERE id=?',sessionKey(req));audit(u,u.id,'demo_sign_in',null,u.role);return openSession(res,u);}
 if(pathname==='/api/login'&&req.method==='POST'){rate(`login:${req.socket.remoteAddress}`,8);const b=await body(req);const u=get('SELECT * FROM users WHERE id=?',String(b.username));const [salt,hash]=(u?.password||'').split(':');if(!salt||typeof b.password!=='string'||b.password.length>256||!timingSafeEqual(Buffer.from(hash,'hex'),scryptSync(b.password,salt,64)))error(401,'Invalid sign-in details');return openSession(res,u);}
 const u=session(req);if(req.method!=='GET'&&req.headers['x-csrf-token']!==u.csrf)error(403,'Session verification failed; reload and try again');
 if(pathname==='/api/logout'&&req.method==='POST'){run('DELETE FROM sessions WHERE id=?',sessionKey(req));res.setHeader('Set-Cookie','civic_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return {ok:true};}
 if(pathname==='/api/events'&&req.method==='GET'){if([...clients].filter(c=>c.userId===u.id).length>=8)error(429,'Too many live connections');res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(`event: ready\ndata: {"revision":${revision}}\n\n`);const c={res,userId:u.id,expires:u.expires,sid:sessionKey(req)};clients.add(c);req.on('close',()=>clients.delete(c));return undefined;}
 if(pathname==='/api/snapshot'&&req.method==='GET'){
  let list=incidentList().filter(i=>canRead(u,i));const q=(url.searchParams.get('q')||'').toLowerCase().slice(0,300);const category=url.searchParams.get('category'),dept=url.searchParams.get('department'),severity=url.searchParams.get('severity'),hours=Number(url.searchParams.get('hours')||0);
  if(category)list=list.filter(i=>i.category===category);if(dept)list=list.filter(i=>i.department===dept);if(severity)list=list.filter(i=>i.severity===severity);if(hours)list=list.filter(i=>Date.now()-i.createdAt<=hours*3600000);
  const applied=[];if(q){let semantic=false;if(/unresolved|open/.test(q)){list=list.filter(i=>!closedStates.includes(i.status));applied.push('Open');semantic=true;}if(/high|critical/.test(q)){list=list.filter(i=>priority(i).score>=50);applied.push('High priority');semantic=true;}if(/school/.test(q)){list=list.filter(i=>/school/i.test(i.description+' '+i.location));applied.push('School mentioned');semantic=true;}if(/sla|breach|due/.test(q)){list=list.filter(i=>!closedStates.includes(i.status)&&i.deadline-Date.now()<86400000);applied.push('SLA due today');semantic=true;}const cat=Object.keys(categories).find(c=>q.includes(c.toLowerCase()));if(cat){list=list.filter(i=>i.category===cat);applied.push(cat);semantic=true;}else if(/road/.test(q)){list=list.filter(i=>i.department==='Roads');applied.push('Roads');semantic=true;}if(!semantic)list=list.filter(i=>`${i.id} ${i.title} ${i.location} ${i.department}`.toLowerCase().includes(q));}
  list.sort((a,b)=>priority(b).score-priority(a).score||a.deadline-b.deadline);const total=list.length,limit=Math.min(200,Math.max(1,Number(url.searchParams.get('limit'))||100)),offset=Math.max(0,Number(url.searchParams.get('offset'))||0);
  const visible=incidentList().filter(i=>canRead(u,i));const active=visible.filter(i=>!closedStates.includes(i.status));const reports=all('SELECT data,incident_id FROM reports WHERE user_id=? ORDER BY created_at DESC LIMIT 100',u.id).map(r=>({...JSON.parse(r.data),incident:dto(incident(r.incident_id),u)}));
  const resDone=visible.filter(i=>i.resolvedAt);return {incidents:list.slice(offset,offset+limit).map(i=>dto(i,u)),total,applied,reports,notifications:all('SELECT id,incident_id AS incidentId,title,at,read FROM notifications WHERE user_id=? ORDER BY at DESC LIMIT 100',u.id),teams:['city','admin','department','field'].includes(u.role)?teams.filter(t=>u.role!=='department'||t.department===u.department).map(t=>({...t,status:active.some(i=>i.teamId===t.id)?'Assigned':'Available'})):[],departments,stats:{active:active.length,reports:visible.reduce((sum,i)=>sum+i.reportCount,0),atRisk:active.filter(i=>i.deadline-Date.now()<3600000).length,resolved:visible.filter(i=>closedStates.includes(i.status)).length,verified:visible.filter(i=>i.status==='CLOSED').length,compliance:resDone.length?Math.round(resDone.filter(i=>i.resolvedAt<=i.deadline).length/resDone.length*100):null},emergency:JSON.parse(get("SELECT value FROM settings WHERE key='emergency'").value),revision,serverTime:Date.now(),demo:DEMO};
 }
 if(pathname==='/api/analyze'&&req.method==='POST'){if(u.role!=='citizen')error(403,'Use the citizen reporting experience');return analyze(reportInput(await body(req)),incidentList());}
 if(pathname==='/api/reports'&&req.method==='POST'){
  if(u.role!=='citizen')error(403,'Citizen sign-in required');const b=await body(req),input=reportInput(b),key=text(req.headers['idempotency-key'],'Submission key',100),payload=createHash('sha256').update(JSON.stringify(b)).digest('hex');
  const result=tx(()=>{const prior=get('SELECT * FROM idempotency WHERE user_id=? AND key=?',u.id,key);if(prior){if(prior.payload!==payload)error(409,'Submission key already used');return JSON.parse(prior.result);}
   const analysis=analyze(input,incidentList());let i;if(b.mergeId){if(!analysis.matches.some(m=>m.id===b.mergeId))error(409,'This incident is no longer a matching open duplicate');i=incident(b.mergeId);i.reportCount++;i.version++;i.updatedAt=Date.now();save(i);audit(u,i.id,'report_merged',i.reportCount-1,i.reportCount);}else{const now=Date.now();i={...input,id:`INC-${randomBytes(4).toString('hex').toUpperCase()}`,title:`${input.category} · ${input.location}`,status:'SUBMITTED',severity:analysis.severity,department:analysis.department,reportCount:1,createdAt:now,updatedAt:now,deadline:now+({CRITICAL:60,HIGH:240,MEDIUM:1440,LOW:2880}[analysis.severity])*60000,version:1,teamId:null,accepted:false,source:'Citizen submitted',analysis,evidence:[]};save(i);run('INSERT INTO history(incident_id,actor,to_state,at,note) VALUES(?,?,?,?,?)',i.id,u.id,'SUBMITTED',now,'Citizen submitted report');change(i,'AI_ANALYZING',u,'Automated triage started');change(i,'TRIAGED',u,'Rules-based triage complete; waiting for operator dispatch');}
   for(const id of (Array.isArray(b.evidence)?b.evidence:[]).slice(0,4)){const e=get('SELECT * FROM evidence WHERE id=? AND user_id=? AND incident_id IS NULL',id,u.id);if(!e)error(400,'Evidence is unavailable');run('UPDATE evidence SET incident_id=?,kind=? WHERE id=?',i.id,'before',id);}
   const r={...input,id:`REP-${randomBytes(4).toString('hex').toUpperCase()}`,incidentId:i.id,createdAt:Date.now(),source:'Citizen submitted'};run('INSERT INTO reports VALUES(?,?,?,?,?)',r.id,u.id,i.id,r.createdAt,JSON.stringify(r));audit(u,r.id,'report_created',null,r);notice(u.id,i.id,`Report ${r.id} received by ${i.department}`);notifyIncident(i,`New report linked to ${i.id}`);const out={report:r,incident:dto(i,u),merged:!!b.mergeId};run('INSERT INTO idempotency VALUES(?,?,?,?)',u.id,key,payload,JSON.stringify(out));return out;});publish();return result;
 }
 const match=pathname.match(/^\/api\/incidents\/([^/]+)(?:\/([^/]+))?$/);
 if(match){const i=incident(decodeURIComponent(match[1]));if(!canRead(u,i))error(403,'This incident is outside your workspace');
  if(req.method==='GET'&&!match[2]){const own=!!get('SELECT id FROM reports WHERE user_id=? AND incident_id=?',u.id,i.id);return {...dto(i,u),history:all('SELECT from_state AS fromState,to_state AS toState,at,note FROM history WHERE incident_id=? ORDER BY id',i.id),evidence:u.role!=='citizen'||own?all('SELECT id,kind,created_at AS at FROM evidence WHERE incident_id=?',i.id):[],clusterReports:['city','admin','department'].includes(u.role)?all('SELECT id,data FROM reports WHERE incident_id=? ORDER BY created_at DESC LIMIT 100',i.id).map(x=>({id:x.id,...JSON.parse(x.data)})):[],audit:['city','admin','department'].includes(u.role)?all('SELECT actor,action,before_value AS beforeValue,after_value AS afterValue,at FROM audit WHERE entity=? ORDER BY id DESC LIMIT 30',i.id):[]};}
  if(req.method!=='POST')error(405,'Method not allowed');const b=await body(req),action=match[2];
  const result=tx(()=>{
   if(action==='confirm'){if(u.role!=='citizen')error(403,'Citizen sign-in required');const added=run('INSERT OR IGNORE INTO participation VALUES(?,?)',u.id,i.id);if(added.changes){i.reportCount++;i.version++;save(i);audit(u,i.id,'community_confirmation',null,u.id);}return dto(i,u);}
   if(b.version!==i.version)error(409,'This incident changed. Refresh and try again.');
   if(action==='assign'){operator(u,i);const team=teams.find(t=>t.id===b.teamId&&t.department===i.department);if(!team)error(400,'Select a team from the responsible department');if(!['TRIAGED','REOPENED','ESCALATED'].includes(i.status))error(409,'This incident is not ready for assignment');const old=i.teamId;i.teamId=team.id;i.accepted=false;change(i,'ASSIGNED',u,`Operator assigned ${team.name}`);audit(u,i.id,'assignment',old,team.id);}
   else if(action==='accept'||action==='start'||action==='resolve'||action==='support'){
    if(u.role!=='field'||u.team!==i.teamId)error(403,'Only the assigned field team can perform this action');
    if(action==='accept'){if(i.status!=='ASSIGNED')error(409,'Assignment is no longer available');i.accepted=true;run('INSERT INTO history(incident_id,actor,from_state,to_state,at,note) VALUES(?,?,?,?,?,?)',i.id,u.id,i.status,i.status,Date.now(),'Field team accepted assignment');audit(u,i.id,'accepted',false,true);}
    if(action==='start'){if(!i.accepted)error(409,'Accept the assignment first');change(i,'IN_PROGRESS',u,'Field team started work');}
    if(action==='support'){if(!['ASSIGNED','IN_PROGRESS','ESCALATED'].includes(i.status))error(409,'Support can only be requested for active work');const note=text(b.note,'Support request',1000);audit(u,i.id,'support_requested',null,note);notifyIncident(i,`Support requested: ${note}`);}
    if(action==='resolve'){if(i.status!=='IN_PROGRESS')error(409,'Start work before resolving');const notes=text(b.notes,'Resolution notes'),evidence=all("SELECT id FROM evidence WHERE incident_id=? AND user_id=? AND kind='after'",i.id,u.id);if(!evidence.length)error(400,'Add an after photo before resolving');const before=get("SELECT id FROM evidence WHERE incident_id=? AND kind='before'",i.id);if(!before)error(400,'Add a before photo before resolving');if(!Number.isFinite(b.lat)||!Number.isFinite(b.lng)||!Number.isFinite(b.accuracy)||b.accuracy>150||distance(i,b)>150)error(400,'Capture GPS within 150 metres of the incident (accuracy 150 m or better)');i.resolution={notes,materials:typeof b.materials==='string'?b.materials.slice(0,1000):'',evidence:evidence.map(e=>e.id),at:Date.now(),location:{lat:b.lat,lng:b.lng,accuracy:b.accuracy},source:'Field submitted · GPS reported by device; not tamper-proof'};change(i,'RESOLVED',u,notes);}
   }else if(action==='verify'){ownReport(u,i);if(i.status!=='RESOLVED')error(409,'The incident is not awaiting verification');if(b.resolved===true){change(i,'CITIZEN_VERIFIED',u,'Citizen confirmed resolution');change(i,'CLOSED',u,'Closed after citizen verification');}else if(b.resolved===false){i.deadline=Date.now()+4*3600000;i.resolvedAt=null;i.accepted=false;change(i,'REOPENED',u,text(b.note||'Citizen reports the issue still exists','Reopening reason',1000));}else error(400,'Choose resolved or still an issue');}
   else if(action==='escalate'){operator(u,i);change(i,'ESCALATED',u,text(b.note,'Escalation reason',1000));}
   else if(action==='split'){operator(u,i);const r=get('SELECT * FROM reports WHERE id=? AND incident_id=?',b.reportId,i.id);if(!r||i.reportCount<=1||closedStates.includes(i.status))error(400,'Choose a linked report in an open cluster');const data=JSON.parse(r.data),fresh={...i,...data,id:`INC-${randomBytes(4).toString('hex').toUpperCase()}`,title:`${data.category} · ${data.location}`,reportCount:1,status:'TRIAGED',teamId:null,accepted:false,createdAt:Date.now(),updatedAt:Date.now(),version:1,resolution:null};save(fresh);run('UPDATE reports SET incident_id=?,data=? WHERE id=?',fresh.id,JSON.stringify({...data,incidentId:fresh.id}),r.id);i.reportCount--;audit(u,i.id,'cluster_split',r.id,fresh.id);notice(r.user_id,fresh.id,'An operator separated your report into its own incident');}
   else error(404,'Unknown action');i.version++;i.updatedAt=Date.now();save(i);return dto(i,u);
  });publish();return result;
 }
 if(pathname==='/api/evidence'&&req.method==='POST'){
  const b=await body(req);if(!['citizen','field'].includes(u.role))error(403,'Evidence can be uploaded by citizens or assigned workers');if(typeof b.data!=='string')error(400,'Choose a photo');const m=b.data.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m)error(400,'Use JPEG, PNG or WebP');const bytes=Buffer.from(m[2],'base64');if(bytes.length>5*1024*1024||bytes.length<20)error(400,'Photo must be under 5 MB');const valid=m[1]==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:m[1]==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(!valid)error(400,'Photo content does not match its format');
  let kind='before';if(b.incidentId){const i=incident(b.incidentId);if(u.role!=='field'||i.teamId!==u.team||!['ASSIGNED','IN_PROGRESS'].includes(i.status))error(403,'Evidence requires an active assignment');kind=b.kind==='after'?'after':'before';}else if(u.role!=='citizen')error(400,'Choose an assignment');const id=randomUUID();writeFileSync(path.join(DATA,'evidence',id),bytes);run('INSERT INTO evidence VALUES(?,?,?,?,?,?)',id,u.id,b.incidentId||null,kind,m[1],Date.now());audit(u,b.incidentId||id,'evidence_uploaded',null,{id,kind});publish();return {id,kind};
 }
 if(pathname.startsWith('/api/evidence/')&&req.method==='GET'){const id=pathname.split('/').pop(),e=get('SELECT * FROM evidence WHERE id=?',id);if(!e)error(404,'Photo not found');const own=e.user_id===u.id;const i=e.incident_id?incident(e.incident_id):null;if(!own&&(!i||!canRead(u,i)||u.role==='citizen'&&!get('SELECT id FROM reports WHERE user_id=? AND incident_id=?',u.id,i.id)))error(403,'Photo is private');res.writeHead(200,{'Content-Type':e.mime,'Cache-Control':'private, max-age=60','Content-Disposition':'inline'});res.end(readFileSync(path.join(DATA,'evidence',id)));return undefined;}
 if(pathname==='/api/notifications/read'&&req.method==='POST'){run('UPDATE notifications SET read=1 WHERE user_id=?',u.id);publish();return {ok:true};}
 if(pathname==='/api/emergency'&&req.method==='POST'){if(!['city','admin'].includes(u.role))error(403,'City operator permission required');const b=await body(req);if(b.confirm!==true)error(400,'Explicit confirmation is required');const previous=JSON.parse(get("SELECT value FROM settings WHERE key='emergency'").value),next={...previous};if(b.action==='activate'||b.action==='deactivate'){next.active=b.action==='activate';next.reason=text(b.reason,'Reason',500);next.at=Date.now();}else if(b.action==='zone'){if(!next.active)error(409,'Activate emergency mode first');const lat=Number(b.lat),lng=Number(b.lng),radius=Number(b.radius);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<6||lat>38||lng<68||lng>98||radius<100||radius>5000||!Number.isFinite(radius))error(400,'Use an Indian location and a radius from 100 to 5000 metres');next.zones=[...next.zones,{id:randomUUID(),name:text(b.name,'Zone name',100),lat,lng,radius}].slice(-20);}else if(b.action==='alert'){if(!next.active)error(409,'Activate emergency mode first');const title=text(b.message,'Alert',500);next.alerts=[...next.alerts,{title,at:Date.now()}].slice(-20);for(const user of all('SELECT id FROM users'))notice(user.id,null,`City alert: ${title}`);}else error(400,'Choose an emergency action');tx(()=>{run("UPDATE settings SET value=? WHERE key='emergency'",JSON.stringify(next));audit(u,'emergency',b.action,previous,next);});publish();return next;}
 if(pathname==='/api/audit'&&req.method==='GET'){if(!['city','admin'].includes(u.role))error(403,'City operator permission required');return all('SELECT actor,entity,action,at FROM audit ORDER BY id DESC LIMIT 100');}
 error(404,'API route not found');
}
const server=http.createServer(async(req,res)=>{
 try{
  const origin=req.headers.origin;if(origin&&!allowedOrigins.has(origin))error(403,'Origin not allowed');if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Vary','Origin');}
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Cache-Control','no-store');
  if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-CSRF-Token,Idempotency-Key'});res.end();return;}
  if(req.method==='POST'&&!origin)error(403,'Origin is required');rate(req.socket.remoteAddress);const url=new URL(req.url,'http://localhost');
  if(!url.pathname.startsWith('/api/')){const whitelist={'/':'index.html','/index.html':'index.html','/civic-ui.js':'civic-ui.js','/civic.css':'civic.css','/leaflet.js':'leaflet.js','/leaflet.css':'leaflet.css','/sw.js':'sw.js','/manifest.webmanifest':'manifest.webmanifest'};const file=whitelist[url.pathname];if(!file||!existsSync(path.join(ROOT,file)))error(404,'Not found');const mime=file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webmanifest')?'application/manifest+json':'text/html';res.setHeader('Content-Type',mime+'; charset=utf-8');res.end(readFileSync(path.join(ROOT,file)));return;}
  const result=await route(req,res,url);if(result!==undefined){res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(result));}
 }catch(e){if(res.headersSent){res.end();return;}res.statusCode=e.status||500;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({error:e.status?e.message:'Something went wrong. Please try again.'}));if(!e.status)console.error(new Date().toISOString(),e);}
});
setInterval(()=>{for(const c of clients){if(c.expires<Date.now()||!get('SELECT id FROM sessions WHERE id=?',c.sid)){c.res.end();clients.delete(c);}else c.res.write(': heartbeat\n\n');}for(const [key,b]of buckets)if(b.until<Date.now())buckets.delete(key);run('DELETE FROM sessions WHERE expires<?',Date.now());},20000).unref();
setInterval(()=>{let changed=false;for(const i of incidentList()){const state=sla(i);if(!closedStates.includes(i.status)&&['At risk','Critical','Breached'].includes(state.risk)){const key=`sla:${i.id}:${i.deadline}:${state.risk}`;if(!get('SELECT key FROM settings WHERE key=?',key)){tx(()=>{run('INSERT INTO settings VALUES(?,?)',key,'sent');notifyIncident(i,`${i.id}: SLA ${state.risk.toLowerCase()}`);});changed=true;}}}if(changed)publish();},30000).unref();
server.listen(PORT,'127.0.0.1',()=>console.log(`Civic OS API http://localhost:${PORT} | ${DEMO?'DEMO ACCOUNTS ENABLED · loopback only':'authenticated mode'} | database ${DATA}`));
process.on('SIGINT',()=>{for(const c of clients)c.res.end();server.close(()=>{db.close();process.exit(0);});});
